/**
 * Everything that touches the filesystem.
 *
 * The engine and the adapters are deliberately I/O-free, which puts the whole burden of *not losing
 * anybody's files* here. Two rules carry it:
 *
 * - **Write only where a manifest says we wrote before.** A generated tree lives at paths Docusaurus
 *   hardcodes — the same paths a site had under source control before migrating. Reconciling blindly
 *   would delete somebody's committed documentation, so an unrecognised target is refused rather than
 *   adopted.
 * - **Write only when the bytes change.** Rewriting an identical file churns its mtime, and a churned
 *   mtime is what makes a dev server rebuild in a loop.
 */

import { createHash } from "node:crypto";
import { copyFileSync, existsSync, mkdirSync, readdirSync, readFileSync, renameSync, rmSync, statSync, unlinkSync, writeFileSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";

/** Marks a directory as ours. Its presence is the only thing that authorises deleting inside it. */
export const SENTINEL = ".docs-overlay-generated";
export const MANIFEST = "manifest.json";
export const MANIFEST_VERSION = 1;

export interface ManifestEntry {
  readonly path: string;
  readonly hash: string;
}

export interface Manifest {
  readonly manifestVersion: number;
  readonly generatedAt: string;
  readonly directories: readonly string[];
  readonly files: readonly ManifestEntry[];
  /**
   * Whatever the caller wants the site's config to read back — for Docusaurus, the `docs` plugin block.
   *
   * This is what stops a site with one config file per deployment target from drifting: both read the
   * same generated file, so `lastVersion` and `versions` cannot disagree, and neither is a string
   * somebody has to remember to bump.
   */
  readonly payload?: unknown;
}

export interface WriteResult {
  readonly written: readonly string[];
  readonly unchanged: readonly string[];
  readonly removed: readonly string[];
  /** Files a previous run wrote that somebody has since edited by hand. Overwritten, but reported. */
  readonly tampered: readonly string[];
}

export const toPosix = (path: string): string => path.replace(/\\/g, "/");

export function walk(root: string, predicate: (relativePath: string) => boolean = () => true): string[] {
  if (!existsSync(root)) return [];
  const out: string[] = [];
  const visit = (dir: string): void => {
    for (const name of readdirSync(dir)) {
      const path = join(dir, name);
      if (statSync(path).isDirectory()) visit(path);
      else {
        const rel = toPosix(relative(root, path));
        if (predicate(rel)) out.push(rel);
      }
    }
  };
  visit(root);
  return out.sort();
}

export const hashOf = (bytes: Buffer | string): string => createHash("sha256").update(bytes).digest("hex").slice(0, 32);

export const hashOfFile = (path: string): string => hashOf(readFileSync(path));

/**
 * Refuses to write into a directory that exists but is not ours.
 *
 * There is no `--force` and no `--adopt`, and that is a decision rather than an omission: adopting a
 * committed tree means the next run deletes it, which is exactly the silent destruction this guard is
 * for. The remedy belongs to a human doing it once, on purpose.
 */
export function assertWritable(siteDir: string, directories: readonly string[]): void {
  for (const directory of directories) {
    const absolute = join(siteDir, directory);
    if (!existsSync(absolute)) continue;
    if (existsSync(join(absolute, SENTINEL))) continue;
    if (readdirSync(absolute).length === 0) continue;

    throw new Error(
      `${toPosix(directory)}/ exists and was not generated by docs-overlay.\n\n` +
        `This tree is now derived from the overlay sources. Check that the content is in your content\n` +
        `directory, then take the old one out of source control and off disk:\n\n` +
        `  git rm -r --cached ${toPosix(directory)}\n` +
        `  rm -rf ${toPosix(directory)}\n`
    );
  }
}

export function readManifest(siteDir: string, outDir: string): Manifest | undefined {
  const path = join(siteDir, outDir, MANIFEST);
  if (!existsSync(path)) return undefined;
  try {
    const manifest = JSON.parse(readFileSync(path, "utf8")) as Manifest;
    return manifest.manifestVersion === MANIFEST_VERSION ? manifest : undefined;
  } catch {
    // A manifest we cannot read is treated as absent, which makes the run reconcile nothing and write
    // everything — inconvenient, never destructive.
    return undefined;
  }
}

export interface PlannedFile {
  readonly path: string;
  readonly bytes: Buffer;
  /** Set when the bytes came from another file, so a copy can be reported as such. */
  readonly from?: string | undefined;
}

/**
 * Writes a planned tree and removes what a previous run wrote and this one does not.
 *
 * `check` mode reports the same three lists without touching anything, which is what lets CI tell a
 * contributor that they edited generated output.
 */
export function reconcile(
  siteDir: string,
  outDir: string,
  directories: readonly string[],
  files: readonly PlannedFile[],
  options: { readonly check?: boolean; readonly clean?: boolean; readonly payload?: unknown } = {}
): WriteResult {
  const check = options.check ?? false;
  const clean = options.clean ?? true;

  const previous = readManifest(siteDir, outDir);
  const previousByPath = new Map((previous?.files ?? []).map(entry => [entry.path, entry.hash]));

  const written: string[] = [];
  const unchanged: string[] = [];
  const tampered: string[] = [];
  const entries: ManifestEntry[] = [];

  for (const file of files) {
    const hash = hashOf(file.bytes);
    entries.push({ path: file.path, hash });

    const absolute = join(siteDir, file.path);
    const onDisk = existsSync(absolute) ? hashOfFile(absolute) : undefined;

    if (onDisk === hash) {
      unchanged.push(file.path);
      continue;
    }

    // Edited by hand: it was ours, its recorded hash matches nothing on disk, and the new plan does not
    // explain the difference either. The edit is lost, so it has to be said out loud.
    const recorded = previousByPath.get(file.path);
    if (onDisk !== undefined && recorded !== undefined && onDisk !== recorded) tampered.push(file.path);

    written.push(file.path);
    if (check) continue;

    mkdirSync(dirname(absolute), { recursive: true });
    // Write then rename, so an interrupted run never leaves a half-written page for Docusaurus to parse.
    const temporary = `${absolute}.docs-overlay-tmp`;
    writeFileSync(temporary, file.bytes);
    renameSync(temporary, absolute);
  }

  const planned = new Set(files.map(file => file.path));
  const removed = [...previousByPath.keys()].filter(path => !planned.has(path)).sort();

  if (!check && clean) {
    for (const path of removed) {
      const absolute = join(siteDir, path);
      if (existsSync(absolute)) unlinkSync(absolute);
    }
    for (const directory of directories) pruneEmpty(join(siteDir, directory), join(siteDir, directory));
  }

  if (!check) {
    for (const directory of directories) {
      const absolute = join(siteDir, directory);
      mkdirSync(absolute, { recursive: true });
      const sentinel = join(absolute, SENTINEL);
      if (!existsSync(sentinel)) {
        writeFileSync(sentinel, "Generated by docs-overlay. Edit the content directory instead; this tree is rewritten on every build.\n");
      }
    }
    const manifest: Manifest = {
      manifestVersion: MANIFEST_VERSION,
      generatedAt: new Date().toISOString(),
      directories,
      files: entries,
      ...(options.payload === undefined ? {} : { payload: options.payload })
    };
    const path = join(siteDir, outDir, MANIFEST);
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, `${JSON.stringify(manifest, undefined, 2)}\n`);
  }

  return { written, unchanged, removed, tampered };
}

/** Removes directories left empty, bottom-up, stopping at the generated root itself. */
function pruneEmpty(directory: string, stopAt: string): void {
  if (!existsSync(directory) || !statSync(directory).isDirectory()) return;
  for (const name of readdirSync(directory)) {
    const child = join(directory, name);
    if (statSync(child).isDirectory()) pruneEmpty(child, stopAt);
  }
  if (resolve(directory) === resolve(stopAt)) return;
  if (readdirSync(directory).length === 0) rmSync(directory, { recursive: false });
}

export const readBytes = (path: string): Buffer => readFileSync(path);
export const readText = (path: string): string => readFileSync(path, "utf8");
export const copy = (from: string, to: string): void => {
  mkdirSync(dirname(to), { recursive: true });
  copyFileSync(from, to);
};
