/**
 * What each version added and what it changed — the one question an overlay can answer for free, and that
 * a plain Docusaurus site can only answer by hand.
 *
 * Sites mark fresh pages with a badge, typically a `sidebar_class_name: new` in the frontmatter. Nothing
 * recomputes it when a version is cut, so it decays: measured on a real 216-page version, 8 of the badges
 * were the wrong one, 65 pages that had changed carried none, and the oldest version — which has no
 * predecessor to be new against — still had six pages claiming to be new.
 *
 * The overlay already knows, because owning a file *is* the diff: a page this version supplies itself is a
 * page it changed, unless the version before it served no such slug, in which case it is a page it added.
 * Derived, the marks cannot decay, and the frontmatter loses a field nobody could keep true.
 *
 * Two deliberate silences:
 *
 * - **The oldest version marks nothing.** Every one of its pages is owned, so a naive reading calls them
 *   all new, which says nothing — "new" is only meaningful against a predecessor.
 * - **Categories are left alone.** A category is not a document; marking one would raise the question of
 *   whether it means its own index page or anything beneath it, and neither answer is obviously right.
 */

import type { VersionId } from "docs-overlay";

import type { DocusaurusSidebars, SidebarItem } from "./sidebars.js";

/** What one version did to the tree it inherited, in doc ids — the space sidebars reference. */
export interface VersionChanges {
  readonly version: VersionId;
  /** Doc ids this version serves at a slug the version before it did not serve at all. */
  readonly added: readonly string[];
  /** Doc ids this version supplies itself, replacing bytes the version before it already served. */
  readonly changed: readonly string[];
}

/** Classes to hang on a changed sidebar entry. Omit one to leave that kind unmarked. */
export interface ChangeClassNames {
  readonly added?: string | undefined;
  readonly changed?: string | undefined;
}

/**
 * Hangs `classNames` on every sidebar entry naming a doc this version added or changed.
 *
 * This covers the entries an author wrote out. It cannot cover an `autogenerated` block, whose items do
 * not exist until Docusaurus expands the directory at build time, long after materialisation — those are
 * the caller's `sidebarItemsGenerator` to annotate, from the same two sets. Two mechanisms for one feature
 * is not a design choice; it is where the framework splits the work.
 *
 * A string item is shorthand for `{ type: "doc", id }` and cannot carry a class, so it is expanded when —
 * and only when — it needs one. An existing class is kept and the new one appended, because a site may
 * already be using `sidebar_class_name` for something this function knows nothing about.
 */
export function annotateSidebars(
  sidebars: DocusaurusSidebars,
  changes: { readonly added: ReadonlySet<string>; readonly changed: ReadonlySet<string> },
  classNames: ChangeClassNames
): DocusaurusSidebars {
  const classOf = (id: string): string | undefined => {
    if (changes.added.has(id)) return classNames.added;
    if (changes.changed.has(id)) return classNames.changed;
    return undefined;
  };

  const annotate = (item: SidebarItem): SidebarItem => {
    if (typeof item === "string") {
      const className = classOf(item);
      return className === undefined ? item : { type: "doc", id: item, className };
    }
    if (item.type === "category") return { ...item, items: item.items.map(annotate) };
    if (item.type !== "doc" && item.type !== "ref") return item;

    const className = classOf(item.id);
    if (className === undefined) return item;
    const existing = item.className === undefined || item.className === "" ? "" : `${item.className} `;
    return { ...item, className: `${existing}${className}` };
  };

  const out: Record<string, SidebarItem[]> = {};
  for (const [name, items] of Object.entries(sidebars)) out[name] = items.map(annotate);
  return out;
}
