/**
 * Public surface of `docs-overlay-docusaurus`.
 *
 * The adapter plans the tree Docusaurus reads from disk and performs no I/O of its own: `materialize()`
 * returns files to copy and files to write, and the caller writes them. Nothing here imports Docusaurus,
 * at runtime or in types — the sidebar shape is described structurally, so a consumer needs no
 * `@docusaurus/*` package installed in order to typecheck against this one.
 */

export type { WithFrontMatter } from "./directives.js";
export { readDocusaurusDirectives, withoutOverlayBlock } from "./directives.js";
export type { DocusaurusMeta, DocsPluginOptions, DocusaurusVersion, Materialization, MaterializedFile, MaterializeOptions } from "./materialize.js";
export { materialize } from "./materialize.js";
export type {
  DocusaurusSidebars,
  PruneMissingOptions,
  SidebarAutogenerated,
  SidebarCategory,
  SidebarCategoryLink,
  SidebarDoc,
  SidebarHtml,
  SidebarItem,
  SidebarLink,
  SidebarMergeContext,
  SidebarMerger
} from "./sidebars.js";
export { pruneMissing, referencesOf, strictSidebars } from "./sidebars.js";
export { DEFAULT_PAGE_EXTENSIONS, declaredSlug, docIdOf, docUrl, docusaurusSlugify } from "./slugs.js";
export type { AliasStub, DeletedStub, RedirectStub, StubTemplates } from "./templates.js";
export { defaultTemplates } from "./templates.js";
