import { createOverlay, type ContentEntry, type Overlay } from "docs-overlay";
import { describe, expect, it } from "vitest";

import { readDocusaurusDirectives } from "./directives.js";
import type { DocusaurusMeta, MaterializedFile } from "./materialize.js";
import { materialize } from "./materialize.js";
import type { DocusaurusSidebars } from "./sidebars.js";
import { docusaurusSlugify } from "./slugs.js";

/** Fixtures are factories, never files: the adapter performs no I/O, and its tests must not either. */
const page = (path: string, frontMatter: Record<string, unknown> = {}): ContentEntry<DocusaurusMeta> => ({
  path,
  kind: "page",
  meta: { frontMatter },
  origin: `/abs/${path}`
});

const sidebarsFile = (version: string, sidebars: DocusaurusSidebars): ContentEntry<DocusaurusMeta> => ({
  path: `${version}/sidebars.json`,
  kind: "meta",
  meta: { sidebars },
  origin: `/abs/${version}/sidebars.json`
});

const overlayOf = (entries: readonly ContentEntry<DocusaurusMeta>[], channels: readonly string[] = ["next"]): Overlay<DocusaurusMeta> =>
  createOverlay<DocusaurusMeta>({
    source: entries,
    channels,
    slugify: docusaurusSlugify(),
    readDirectives: readDocusaurusDirectives()
  });

const written = (files: readonly MaterializedFile[], path: string): string | undefined =>
  files.find((file): file is Extract<MaterializedFile, { kind: "write" }> => file.kind === "write" && file.path === path)?.contents;

const copies = (files: readonly MaterializedFile[]): readonly { path: string; from: string }[] =>
  files.filter((file): file is Extract<MaterializedFile, { kind: "copy" }> => file.kind === "copy").map(({ path, from }) => ({ path, from }));

const BASE: DocusaurusSidebars = { docs: ["index", { type: "category", label: "Guide", items: [{ type: "autogenerated", dirName: "guide" }] }] };

describe("materialize", () => {
  it("writes each version's pages at fixed Docusaurus paths, and the channel where docs.path can point", () => {
    const overlay = overlayOf([
      page("1.0.0/index.md"),
      page("1.0.0/guide/intro.md"),
      sidebarsFile("1.0.0", BASE),
      page("2.0.0/guide/intro.md"),
      page("next/guide/extra.md")
    ]);

    const result = materialize(overlay, { routeBasePath: "/" });

    // 1.0.0 keeps its own copy; 2.0.0 overrides intro and inherits index; next inherits both and adds one.
    expect(copies(result.files)).toEqual([
      { path: "versioned_docs/version-1.0.0/index.md", from: "/abs/1.0.0/index.md" },
      { path: "versioned_docs/version-1.0.0/guide/intro.md", from: "/abs/1.0.0/guide/intro.md" },
      { path: "versioned_docs/version-2.0.0/index.md", from: "/abs/1.0.0/index.md" },
      { path: "versioned_docs/version-2.0.0/guide/intro.md", from: "/abs/2.0.0/guide/intro.md" },
      { path: ".docs-overlay/current/index.md", from: "/abs/1.0.0/index.md" },
      { path: ".docs-overlay/current/guide/intro.md", from: "/abs/2.0.0/guide/intro.md" },
      { path: ".docs-overlay/current/guide/extra.md", from: "/abs/next/guide/extra.md" }
    ]);
  });

  it("rewrites an inherited page into the browsing version's folder, not the folder that defined it", () => {
    const overlay = overlayOf([page("1.0.0/a.md"), sidebarsFile("1.0.0", { docs: ["a"] }), page("2.0.0/b.md")]);
    const result = materialize(overlay);

    const inherited = copies(result.files).find(file => file.path === "versioned_docs/version-2.0.0/a.md");
    // The destination is 2.0.0's folder while the bytes still come from 1.0.0's file — which is the whole
    // point: writing it at its own source path would drop it into the wrong version.
    expect(inherited).toEqual({ path: "versioned_docs/version-2.0.0/a.md", from: "/abs/1.0.0/a.md" });
  });

  it("lists released versions newest first and excludes the channel", () => {
    const overlay = overlayOf([page("1.0.0/a.md"), sidebarsFile("1.0.0", { docs: ["a"] }), page("2.0.0/b.md"), page("next/c.md")]);
    const result = materialize(overlay);

    expect(written(result.files, "versions.json")).toBe(`${JSON.stringify(["2.0.0", "1.0.0"], undefined, 2)}\n`);
  });

  it("derives the docs plugin options, so the two site configs cannot disagree", () => {
    const overlay = overlayOf([page("1.0.0/a.md"), sidebarsFile("1.0.0", { docs: ["a"] }), page("2.0.0/b.md"), page("next/c.md")]);
    const result = materialize(overlay, { labels: { next: "Next 🚧" } });

    expect(result.docsOptions).toEqual({
      path: ".docs-overlay/current",
      sidebarPath: "./.docs-overlay/sidebars/current.json",
      includeCurrentVersion: true,
      lastVersion: "2.0.0",
      versions: {
        "1.0.0": { label: "1.0.0", path: "1.0.0" },
        // `lastVersion` already serves it at the root, so it gets no path of its own.
        "2.0.0": { label: "2.0.0" },
        current: { label: "Next 🚧", path: "next" }
      }
    });
  });

  it("prunes a doc the inherited sidebar names but the version tombstoned", () => {
    // The real case: 11.13.0's sidebar lists atomic/changelog, and 11.14.0 removes that page. Left alone,
    // Docusaurus fails with `document with id "atomic/changelog" not found`.
    const overlay = overlayOf([
      page("1.0.0/index.md"),
      page("1.0.0/legacy.md"),
      sidebarsFile("1.0.0", { docs: ["index", "legacy"] }),
      page("2.0.0/legacy.md", { overlay: { deleted: true } })
    ]);

    const result = materialize(overlay);

    expect(JSON.parse(written(result.files, "versioned_sidebars/version-1.0.0-sidebars.json")!)).toEqual({ docs: ["index", "legacy"] });
    expect(JSON.parse(written(result.files, "versioned_sidebars/version-2.0.0-sidebars.json")!)).toEqual({ docs: ["index"] });
  });

  it("drops an autogenerated block whose directory holds nothing here", () => {
    const overlay = overlayOf([page("1.0.0/index.md"), sidebarsFile("1.0.0", BASE)]);
    const result = materialize(overlay);

    expect(JSON.parse(written(result.files, "versioned_sidebars/version-1.0.0-sidebars.json")!)).toEqual({ docs: ["index"] });
    expect(result.diagnostics.some(diagnostic => diagnostic.message.includes('generates from "guide"'))).toBe(true);
  });

  it("generates a real route for a renamed page's old slug, so an internal link to it still resolves", () => {
    const overlay = overlayOf([
      page("1.0.0/guide/old-api.md"),
      sidebarsFile("1.0.0", { docs: [{ type: "doc", id: "guide/old-api" }] }),
      page("2.0.0/guide/new-api.md", { overlay: { renamedFrom: "guide/old-api" } })
    ]);

    const result = materialize(overlay, { routeBasePath: "/" });

    const stub = written(result.files, "versioned_docs/version-2.0.0/guide/old-api.mdx");
    expect(stub).toContain("unlisted: true");
    // 2.0.0 is the newest release, so it is `lastVersion` and served at the root: no version segment.
    // That is the URL shape a plain Docusaurus site produces, which is why nothing linked externally moves.
    expect(stub).toContain('<Redirect to="/guide/new-api" />');
    // One per version that still answers for the old slug: a rename in 2.0.0 keeps redirecting in the
    // channel that inherits from it, which is what stops a valid external link from 404ing after a cut.
    expect(result.redirects).toEqual([
      { from: "/guide/old-api", to: "/guide/new-api", permanent: true },
      { from: "/next/guide/old-api", to: "/next/guide/new-api", permanent: true }
    ]);
    expect(written(result.files, ".docs-overlay/current/guide/old-api.mdx")).toBeDefined();
  });

  it("rewrites a sidebar reference to a renamed doc instead of dropping it", () => {
    const overlay = overlayOf([
      page("1.0.0/guide/old-api.md"),
      sidebarsFile("1.0.0", { docs: ["guide/old-api"] }),
      page("2.0.0/guide/new-api.md", { overlay: { renamedFrom: "guide/old-api" } })
    ]);

    const result = materialize(overlay);
    expect(JSON.parse(written(result.files, "versioned_sidebars/version-2.0.0-sidebars.json")!)).toEqual({ docs: ["guide/new-api"] });
  });

  it("explains a removed page instead of leaving a 404, and names where it still exists", () => {
    const overlay = overlayOf([
      page("1.0.0/gone.md"),
      page("1.0.0/guide/modern.md"),
      sidebarsFile("1.0.0", { docs: ["gone", "guide/modern"] }),
      page("2.0.0/gone.md", { overlay: { deleted: true, replacedBy: "guide/modern" } })
    ]);

    const result = materialize(overlay, { routeBasePath: "/" });
    const stub = written(result.files, "versioned_docs/version-2.0.0/gone.mdx");

    expect(stub).toContain("removed in 2.0.0");
    expect(stub).toContain("This page was removed in 2.0.0.");
    expect(stub).toContain("[1.0.0](/1.0.0/gone)");
    expect(stub).toContain("See [guide/modern](/guide/modern)");
  });

  it("takes replacedBy as a slug, not a doc id — the two differ for an index page", () => {
    // The trap a Docusaurus author walks into: they think in doc ids, because that is what sidebars use.
    // `index.md` has the doc id `index` and the slug `` — so `replacedBy: index` names a slug nothing
    // serves, and the reader is sent to a page that does not exist.
    const overlay = overlayOf([
      page("1.0.0/gone.md"),
      page("1.0.0/index.md"),
      sidebarsFile("1.0.0", { docs: ["index", "gone"] }),
      page("2.0.0/gone.md", { overlay: { deleted: true, replacedBy: "index" } })
    ]);

    const result = materialize(overlay, { routeBasePath: "/" });

    expect(result.diagnostics.some(diagnostic => diagnostic.code === "redirect-target-missing")).toBe(true);
  });

  it("puts a stub at <slug>/index.mdx when the slug is also a directory", () => {
    const overlay = overlayOf([
      page("1.0.0/api.md"),
      page("1.0.0/api/one.md"),
      sidebarsFile("1.0.0", { docs: ["api", "api/one"] }),
      page("2.0.0/api.md", { overlay: { deleted: true } })
    ]);

    const result = materialize(overlay);
    // `api` still names a directory holding `one.md`, so the stub cannot be `api.mdx` beside it.
    expect(written(result.files, "versioned_docs/version-2.0.0/api/index.mdx")).toBeDefined();
  });

  it("reports more than one channel rather than silently serving one of them", () => {
    const overlay = overlayOf([page("1.0.0/a.md"), sidebarsFile("1.0.0", { docs: ["a"] }), page("next/b.md"), page("canary/c.md")], ["next", "canary"]);
    const result = materialize(overlay);

    expect(result.diagnostics.some(diagnostic => diagnostic.message.includes("single current version"))).toBe(true);
  });

  it("reports a version with no navigation at all", () => {
    const overlay = overlayOf([page("1.0.0/a.md")]);
    const result = materialize(overlay);

    expect(result.diagnostics.some(diagnostic => diagnostic.message.includes("no sidebars.json"))).toBe(true);
  });

  it("names only the directories it owns, so a writer can prune inside them and nowhere else", () => {
    const overlay = overlayOf([page("1.0.0/a.md"), sidebarsFile("1.0.0", { docs: ["a"] })]);
    const result = materialize(overlay, { outDir: "_generated", pluginId: "community" });

    expect(result.directories).toEqual(["_generated", "community_versioned_docs", "community_versioned_sidebars"]);
    expect(written(result.files, "community_versions.json")).toBeDefined();
    expect(copies(result.files)[0]?.path).toBe("community_versioned_docs/version-1.0.0/a.md");
  });
});
