/**
 * Navigation, and why inheritance has to prune it rather than complete it.
 *
 * The Fumadocs adapter keeps one `meta.json` per directory. Here a version keeps one `sidebars.json` at
 * its root, which the engine inherits whole like any other metadata file. The contrast is the useful
 * part: the engine applied the same inheritance to both without learning either format.
 *
 * What differs is the direction of the fix. An inherited Fumadocs `pages` list that omits a new page
 * makes it invisible, so `appendRest()` **completes** it. An inherited Docusaurus sidebar that names a
 * doc this version no longer has makes Docusaurus **throw** — `Invalid sidebar file … document with id
 * "x" not found` — so the merger has to **prune**. A harder failure, and a mirror-image remedy.
 */

import type { Diagnostic, DiagnosticSink, VersionId } from "docs-overlay";

/**
 * The sidebar shape, described structurally rather than imported.
 *
 * Only what the merger actually walks is modelled. Taking `@docusaurus/plugin-content-docs` as a
 * type-only peer would force every consumer to install it to typecheck, and buy nothing: the sidebar is
 * JSON, and this adapter never calls Docusaurus.
 */
export type SidebarItem = string | SidebarDoc | SidebarCategory | SidebarLink | SidebarAutogenerated | SidebarHtml;

export interface SidebarDoc {
  readonly type: "ref" | "doc";
  readonly id: string;
  readonly label?: string;
  readonly className?: string;
}

export interface SidebarCategory {
  readonly type: "category";
  readonly label: string;
  readonly items: readonly SidebarItem[];
  readonly link?: SidebarCategoryLink;
  readonly collapsed?: boolean;
  readonly collapsible?: boolean;
  readonly className?: string;
}

export type SidebarCategoryLink = { readonly type: "doc"; readonly id: string } | { readonly type: "generated-index"; readonly [key: string]: unknown };

export interface SidebarLink {
  readonly type: "link";
  readonly href: string;
  readonly label: string;
}

export interface SidebarAutogenerated {
  readonly type: "autogenerated";
  readonly dirName: string;
}

export interface SidebarHtml {
  readonly type: "html";
  readonly value: string;
  readonly [key: string]: unknown;
}

/** One named sidebar per key, which is what `sidebars.js` exports and `versioned_sidebars/*.json` holds. */
export type DocusaurusSidebars = Readonly<Record<string, readonly SidebarItem[]>>;

export interface SidebarMergeContext {
  readonly version: VersionId;
  /** False when this version authored the file, true when it comes from an ancestor. */
  readonly inherited: boolean;
  /** Doc ids this version actually materialises. */
  readonly docIds: ReadonlySet<string>;
  /** Directories that hold at least one page, so an `autogenerated` block has something to generate. */
  readonly dirNames: ReadonlySet<string>;
  /** Doc ids the version that authored the file had, which is how a real removal is told from a typo. */
  readonly authoredDocIds: ReadonlySet<string>;
  /** Doc id a removed one was renamed to, when the overlay knows of one. */
  readonly renamedTo: (docId: string) => string | undefined;
  readonly onDiagnostic: DiagnosticSink;
}

export type SidebarMerger = (sidebars: DocusaurusSidebars, context: SidebarMergeContext) => DocusaurusSidebars;

export interface PruneMissingOptions {
  /** Rewrite a reference to a renamed doc instead of dropping it. On by default: a page that moved should keep its place in the navigation without anyone editing the sidebar. */
  readonly rewriteRenames?: boolean | undefined;
}

/**
 * Drops what a version cannot serve, and rewrites what merely moved.
 *
 * Deliberately asymmetric with the content model, and the symmetry is worth naming: **removals are
 * automatic, additions are declared.** Nothing is ever added to a sidebar here — the site's categories
 * are `autogenerated`, so a new page appears by itself, whereas a new *category* is an editorial act.
 */
export function pruneMissing(options: PruneMissingOptions = {}): SidebarMerger {
  const rewriteRenames = options.rewriteRenames ?? true;

  return (sidebars, context) => {
    const result: Record<string, readonly SidebarItem[]> = {};

    for (const [name, items] of Object.entries(sidebars)) {
      const kept = items.map(item => visit(item, name, context, rewriteRenames)).filter((item): item is SidebarItem => item !== undefined);

      if (kept.length === 0 && items.length > 0) {
        context.onDiagnostic({
          code: "meta-pages-completed",
          severity: "error",
          message: `${context.version}: sidebar "${name}" has nothing left after removing what this version does not serve.`,
          version: context.version
        });
      }
      result[name] = kept;
    }

    return result;
  };
}

/** Changes nothing, so a build fails on what pruning would have hidden. The counterpart of the engine's `strictMeta`. */
export function strictSidebars(): SidebarMerger {
  return sidebars => sidebars;
}

function visit(item: SidebarItem, sidebar: string, context: SidebarMergeContext, rewriteRenames: boolean): SidebarItem | undefined {
  if (typeof item === "string") return resolveDoc(item, sidebar, context, rewriteRenames);

  switch (item.type) {
    case "doc":
    case "ref": {
      const id = resolveDoc(item.id, sidebar, context, rewriteRenames);
      return id === undefined ? undefined : { ...item, id };
    }

    case "autogenerated": {
      // A `dirName` that no longer exists is fatal to Docusaurus, and this is the ordinary way a whole
      // product section disappears between versions.
      if (context.dirNames.has(item.dirName)) return item;
      context.onDiagnostic({
        code: "meta-pages-completed",
        severity: context.inherited ? "warning" : "error",
        message:
          `${context.version}: sidebar "${sidebar}" generates from "${item.dirName}", which holds no page here` +
          `${context.inherited ? " — dropped from the inherited sidebar" : ""}.`,
        version: context.version
      });
      return undefined;
    }

    case "category": {
      const items = item.items.map(child => visit(child, sidebar, context, rewriteRenames)).filter((child): child is SidebarItem => child !== undefined);
      // Docusaurus refuses a category with no items, so an emptied one has to go rather than be emptied.
      if (items.length === 0) return undefined;

      const link = resolveLink(item.link, sidebar, context, rewriteRenames);
      return link === undefined ? { ...withoutLink(item), items } : { ...item, items, link };
    }

    default:
      return item;
  }
}

function resolveDoc(id: string, sidebar: string, context: SidebarMergeContext, rewriteRenames: boolean): string | undefined {
  if (context.docIds.has(id)) return id;

  if (rewriteRenames) {
    const renamed = context.renamedTo(id);
    if (renamed !== undefined && context.docIds.has(renamed)) return renamed;
  }

  // Severity carries the distinction that matters to whoever reads the build log: a doc the authoring
  // version had is an ordinary removal reaching an inherited sidebar; a doc it never had is a typo.
  context.onDiagnostic({
    code: "meta-pages-completed",
    severity: context.authoredDocIds.has(id) ? "warning" : "error",
    message: `${context.version}: sidebar "${sidebar}" names the doc "${id}", which this version does not serve.`,
    version: context.version
  });
  return undefined;
}

function resolveLink(
  link: SidebarCategoryLink | undefined,
  sidebar: string,
  context: SidebarMergeContext,
  rewriteRenames: boolean
): SidebarCategoryLink | undefined {
  if (link === undefined || link.type !== "doc") return link;
  const id = resolveDoc(link.id, sidebar, context, rewriteRenames);
  // A category whose link is gone keeps its items; only the link goes. Dropping the whole category would
  // remove pages that are perfectly fine.
  return id === undefined ? undefined : { type: "doc", id };
}

function withoutLink(category: SidebarCategory): Omit<SidebarCategory, "link"> {
  const { link: _link, ...rest } = category;
  return rest;
}

/** Doc ids and `autogenerated` directories a sidebar set references, for a caller that wants to check them. */
export function referencesOf(sidebars: DocusaurusSidebars): { readonly docIds: readonly string[]; readonly dirNames: readonly string[] } {
  const docIds: string[] = [];
  const dirNames: string[] = [];

  const walk = (item: SidebarItem): void => {
    if (typeof item === "string") return void docIds.push(item);
    if (item.type === "doc" || item.type === "ref") return void docIds.push(item.id);
    if (item.type === "autogenerated") return void dirNames.push(item.dirName);
    if (item.type !== "category") return;
    if (item.link?.type === "doc") docIds.push(item.link.id);
    for (const child of item.items) walk(child);
  };

  for (const items of Object.values(sidebars)) for (const item of items) walk(item);
  return { docIds, dirNames };
}

export type { Diagnostic };
