/**
 * The pages a version serves that are not pages.
 *
 * `getEntries()` answers for more slugs than `getPages()` does: an alias, an old slug that now
 * redirects, a page removed in this version. Each wants a different answer, and on a statically exported
 * site every one of them has to be a **real route** — an un-generated route is a 404, not a redirect.
 *
 * That is also why this adapter generates stub pages rather than leaning on
 * `@docusaurus/plugin-client-redirects`: that plugin runs in `postBuild`, after the route registry is
 * fixed, so `onBrokenLinks: 'throw'` never sees its targets. An internal link to a renamed page would
 * fail the build even though the redirect exists. A stub is a route, so the check passes — and it saves
 * the site a dependency.
 */

import type { Slug, VersionId } from "docs-overlay";

export interface RedirectStub {
  readonly slug: Slug;
  /** Where the reader is sent. */
  readonly to: Slug;
  readonly url: string;
  readonly permanent: boolean;
}

export interface AliasStub {
  readonly slug: Slug;
  /** The page's real slug, which the canonical link should name. */
  readonly canonical: Slug;
  readonly url: string;
}

export interface DeletedStub {
  readonly slug: Slug;
  readonly deletedIn: VersionId;
  readonly lastAvailable: VersionId | undefined;
  readonly lastAvailableUrl: string | undefined;
  readonly replacedBy: Slug | undefined;
  readonly replacedByUrl: string | undefined;
}

export interface StubTemplates {
  redirect(stub: RedirectStub): string;
  alias(stub: AliasStub): string;
  deleted(stub: DeletedStub): string;
}

/**
 * `unlisted: true` keeps a stub out of autogenerated sidebars, the search index and the sitemap while
 * still producing the route — which is exactly the combination wanted here.
 */
const frontMatter = (entries: readonly (readonly [string, string])[]): string =>
  ["---", ...entries.map(([key, value]) => `${key}: ${value}`), "unlisted: true", "---", ""].join("\n");

export const defaultTemplates: StubTemplates = {
  redirect: stub =>
    // Both halves are needed: `<Redirect>` moves a reader who has JavaScript, and the meta refresh plus
    // the visible link serve one who does not — including a crawler.
    `${frontMatter([
      ["title", `Moved to ${stub.to.join("/")}`],
      ["description", `This page moved to ${stub.url}.`]
    ])}
import Redirect from "@docusaurus/Redirect";
import Head from "@docusaurus/Head";

<Head>
  <meta httpEquiv="refresh" content={\`0; url=${stub.url}\`} />
  <link rel="canonical" href="${stub.url}" />
</Head>

<Redirect to="${stub.url}" />

This page moved to [${stub.to.join("/")}](${stub.url}).
`,

  alias: stub =>
    `${frontMatter([
      ["title", stub.canonical.join("/")],
      ["description", `Also reachable at ${stub.url}.`]
    ])}
import Head from "@docusaurus/Head";

<Head>
  <link rel="canonical" href="${stub.url}" />
</Head>

This page also lives at [${stub.canonical.join("/")}](${stub.url}), which is its canonical location.
`,

  // The visible payoff over a plain Docusaurus site: a reader who follows an old link is told what
  // happened and where the page still exists, instead of meeting a bare 404.
  deleted: stub => {
    const lines = [`This page was removed in ${stub.deletedIn}.`, ""];
    if (stub.lastAvailable !== undefined && stub.lastAvailableUrl !== undefined) {
      lines.push(`The last version that still serves it is [${stub.lastAvailable}](${stub.lastAvailableUrl}).`, "");
    }
    if (stub.replacedBy !== undefined && stub.replacedByUrl !== undefined) {
      lines.push(`See [${stub.replacedBy.join("/")}](${stub.replacedByUrl}) instead.`, "");
    }
    return `${frontMatter([
      ["title", `${stub.slug.at(-1) ?? "Page"} (removed in ${stub.deletedIn})`],
      ["description", `Removed in ${stub.deletedIn}.`]
    ])}
${lines.join("\n")}`;
  }
};
