/**
 * The pages a version serves that are not pages.
 *
 * `getEntries()` answers for more slugs than `getPages()` does: an alias, an old slug that now
 * redirects, a page removed in this version. Each wants a different answer, and on a statically exported
 * site every one of them has to be a **real route** — an un-generated route is a 404, not a redirect.
 *
 * That is also why this adapter generates stub pages rather than leaning on
 * `@docusaurus/plugin-client-redirects`: that plugin runs in `postBuild`, after the route registry is
 * fixed, so `onBrokenLinks: 'throw'` never sees its targets. An internal link to a renamed page would
 * fail the build even though the redirect exists. A stub is a route, so the check passes — and it saves
 * the site a dependency.
 *
 * Every path below is **site-root-relative and carries no `baseUrl`**; the generated page adds it at
 * build time with `useBaseUrl`. That is what makes the generated tree identical for every deployment
 * target. A site with two of them — one public, one on an enterprise domain — would otherwise need one
 * materialisation per target, and `materialize --check` in CI would depend on which target ran last.
 */

import type { Slug, VersionId } from "docs-overlay";

export interface RedirectStub {
  readonly slug: Slug;
  /** Where the reader is sent. */
  readonly to: Slug;
  /** Site-root-relative path of `to`, without `baseUrl`. */
  readonly path: string;
  readonly permanent: boolean;
}

export interface AliasStub {
  readonly slug: Slug;
  /** The page's real slug, which the canonical link should name. */
  readonly canonical: Slug;
  /** Site-root-relative path of `canonical`, without `baseUrl`. */
  readonly path: string;
}

export interface DeletedStub {
  readonly slug: Slug;
  readonly deletedIn: VersionId;
  readonly lastAvailable: VersionId | undefined;
  /** Where this page still exists, without `baseUrl`. */
  readonly lastAvailablePath: string | undefined;
  readonly replacedBy: Slug | undefined;
  readonly replacedByPath: string | undefined;
}

export interface StubTemplates {
  redirect(stub: RedirectStub): string;
  alias(stub: AliasStub): string;
  deleted(stub: DeletedStub): string;
}

/**
 * `unlisted: true` keeps a stub out of autogenerated sidebars, the search index and the sitemap while
 * still producing the route — verified on a real build: the route answers 200 and the slug does not
 * appear in the rendered sidebar.
 */
const frontMatter = (entries: readonly (readonly [string, string])[]): string =>
  ["---", ...entries.map(([key, value]) => `${key}: ${value}`), "unlisted: true", "---", ""].join("\n");

export const defaultTemplates: StubTemplates = {
  // Both halves are needed: `<Redirect>` moves a reader who has JavaScript, and the meta refresh plus the
  // visible link serve one who does not — including a crawler. `Redirect` comes from
  // `@docusaurus/router`; there is no `@docusaurus/Redirect` alias, and asking for one fails the build
  // with `Module not found`.
  redirect: stub =>
    [
      frontMatter([
        ["title", `Moved to ${stub.to.join("/")}`],
        ["description", `This page moved to ${stub.path}.`]
      ]),
      `import { Redirect } from "@docusaurus/router";`,
      `import Head from "@docusaurus/Head";`,
      `import useBaseUrl from "@docusaurus/useBaseUrl";`,
      ``,
      // Inline in each expression rather than hoisted into `export const`. An `export` in MDX is a
      // *module*-level binding, so the hook would run outside the component and React rejects it — static
      // generation fails for every such page. Calling it three times is fine: same hook, same order, every
      // render.
      `<Head>`,
      `  <meta httpEquiv="refresh" content={\`0; url=\${useBaseUrl("${stub.path}")}\`} />`,
      `  <link rel="canonical" href={useBaseUrl("${stub.path}")} />`,
      `</Head>`,
      ``,
      `<Redirect to={useBaseUrl("${stub.path}")} />`,
      ``,
      `This page moved to [${stub.to.join("/")}](${stub.path}).`,
      ``
    ].join("\n"),

  alias: stub =>
    [
      frontMatter([
        ["title", stub.canonical.join("/")],
        ["description", `Also reachable at ${stub.path}.`]
      ]),
      `import Head from "@docusaurus/Head";`,
      `import useBaseUrl from "@docusaurus/useBaseUrl";`,
      ``,
      `<Head>`,
      `  <link rel="canonical" href={useBaseUrl("${stub.path}")} />`,
      `</Head>`,
      ``,
      `This page also lives at [${stub.canonical.join("/")}](${stub.path}), which is its canonical location.`,
      ``
    ].join("\n"),

  // The visible payoff over a plain Docusaurus site: a reader who follows an old link is told what
  // happened and where the page still exists, instead of meeting a bare 404.
  deleted: stub => {
    const body = [`This page was removed in ${stub.deletedIn}.`, ""];
    if (stub.lastAvailable !== undefined && stub.lastAvailablePath !== undefined) {
      body.push(`The last version that still serves it is [${stub.lastAvailable}](${stub.lastAvailablePath}).`, "");
    }
    if (stub.replacedBy !== undefined && stub.replacedByPath !== undefined) {
      body.push(`See [${stub.replacedBy.join("/")}](${stub.replacedByPath}) instead.`, "");
    }
    return [
      frontMatter([
        ["title", `${stub.slug.at(-1) ?? "Page"} (removed in ${stub.deletedIn})`],
        ["description", `Removed in ${stub.deletedIn}.`]
      ]),
      ...body
    ].join("\n");
  }
};
